name: Publish Release

on:
  create:
    tags:
      - '\d+\.\d+\.\d+'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3

      - uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: ${{ vars.GRADLE_JAVA_VERSION }}

      - name: Github Packages
        run: ./gradlew --stacktrace publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
